

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    padding: 0,
  },
  background: {
    flex: 1,
    width: '100%',
    height: '100%',
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    backgroundColor: "#C8102E",
    paddingLeft: 0,
  },
  logoHeader: {
    width: 105,
    height: 105,
    resizeMode: "cover",
    marginTop: -15,
    marginBottom: -10,
    marginLeft: -15,
  },
  headerTitle: {
    color: "#fff",
    fontSize: 24,
    fontWeight: "800",
    lineHeight: 28,
    marginLeft: -10,
  },
  headerNumber: {
    color: "#fff",
    fontSize: 13,
  },
  container: {
    flexGrow: 1,
    padding: 20,
  },
  title: {
    fontSize: 24,
    fontWeight: '700',
    marginBottom: 20,
    color: '#2f2f2fff',
    textAlign: 'center',
  },
  description: {
    fontSize: 16,
    lineHeight: 24,
    color: '#333',
    textAlign: 'center',
    marginBottom: 25,
  },
  section: {
    marginBottom: 25,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#C8102E',
    marginBottom: 15,
    textAlign: 'center',
  },
  card: {
    backgroundColor: '#f8f9fa',
    padding: 20,
    borderRadius: 12,
    marginBottom: 15,
    borderLeftWidth: 4,
    borderLeftColor: '#1E2A78',
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#1E2A78',
    marginVertical: 10,
  },
  cardText: {
    fontSize: 14,
    lineHeight: 20,
    color: '#555',
  },
  valuesContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  valueItem: {
    width: '48%',
    alignItems: 'center',
    backgroundColor: '#f0f4ff',
    padding: 15,
    borderRadius: 8,
    marginBottom: 10,
  },
  valueText: {
    marginTop: 8,
    fontSize: 14,
    fontWeight: '600',
    color: '#1E2A78',
    textAlign: 'center',
  },
  contactItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
    backgroundColor: '#f8f9fa',
    borderRadius: 8,
    marginBottom: 10,
  },
  contactText: {
    marginLeft: 12,
    fontSize: 16,
    color: '#333',
  },
  backButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
    marginBottom: 10,
    padding: 15,
    backgroundColor: '#fff',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#031666ff',
  },
  backButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#031666ff',
    marginLeft: 8,
  },
  footer: {
    alignItems: "center",
    padding: 15,
    backgroundColor: "#1E2A78",
  },
  footerText: {
    fontSize: 14,
    color: "#ffffffff",
    marginBottom: 5,
  },
});
